const AVAILABLE_EVENTS: Record<string, string> = {
  FORM_SUBMIT: 'NATIVE_APM_FORM_SUBMIT',
  SUCCESS: 'NATIVE_APM_PAYMENT_SUCCESS',
  ERROR: 'NATIVE_APM_PAYMENT_ERROR',
};

export default AVAILABLE_EVENTS;
