module ProcessOut {
  // These country codes comes from API code list
  // https://github.com/processout/api/blob/f97803020e55cc622b1de501ea77fe634096973a/module/sharedkernel/domain/phone/dialing_codes.go#L61
  export const COUNTRY_CODE_TO_PHONE_PREFIX = {
    AF: { prefix: "+93", name: "Afghanistan" },
    AL: { prefix: "+355", name: "Albania" },
    DZ: { prefix: "+213", name: "Algeria" },
    AS: { prefix: "+1-684", name: "American Samoa" },
    AD: { prefix: "+376", name: "Andorra" },
    AO: { prefix: "+244", name: "Angola" },
    AI: { prefix: "+1-264", name: "Anguilla" },
    AG: { prefix: "+1-268", name: "Antigua and Barbuda" },
    AR: { prefix: "+54", name: "Argentina" },
    AM: { prefix: "+374", name: "Armenia" },
    AW: { prefix: "+297", name: "Aruba" },
    AU: { prefix: "+61", name: "Australia" },
    AT: { prefix: "+43", name: "Austria" },
    AZ: { prefix: "+994", name: "Azerbaijan" },
    BS: { prefix: "+1-242", name: "Bahamas" },
    BH: { prefix: "+973", name: "Bahrain" },
    BD: { prefix: "+880", name: "Bangladesh" },
    BB: { prefix: "+1-246", name: "Barbados" },
    BY: { prefix: "+375", name: "Belarus" },
    BE: { prefix: "+32", name: "Belgium" },
    BZ: { prefix: "+501", name: "Belize" },
    BJ: { prefix: "+229", name: "Benin" },
    BM: { prefix: "+1-441", name: "Bermuda" },
    BT: { prefix: "+975", name: "Bhutan" },
    BO: { prefix: "+591", name: "Bolivia" },
    BQ: { prefix: "+599", name: "Bonaire, Sint Eustatius and Saba" },
    BA: { prefix: "+387", name: "Bosnia and Herzegovina" },
    BW: { prefix: "+267", name: "Botswana" },
    BR: { prefix: "+55", name: "Brazil" },
    IO: { prefix: "+246", name: "British Indian Ocean Territory" },
    VG: { prefix: "+1-284", name: "British Virgin Islands" },
    BN: { prefix: "+673", name: "Brunei" },
    BG: { prefix: "+359", name: "Bulgaria" },
    BF: { prefix: "+226", name: "Burkina Faso" },
    BI: { prefix: "+257", name: "Burundi" },
    KH: { prefix: "+855", name: "Cambodia" },
    CM: { prefix: "+237", name: "Cameroon" },
    CA: { prefix: "+1", name: "Canada" },
    CV: { prefix: "+238", name: "Cape Verde" },
    KY: { prefix: "+1-345", name: "Cayman Islands" },
    CF: { prefix: "+236", name: "Central African Republic" },
    TD: { prefix: "+235", name: "Chad" },
    CL: { prefix: "+56", name: "Chile" },
    CN: { prefix: "+86", name: "China" },
    CX: { prefix: "+61", name: "Christmas Island" },
    CC: { prefix: "+61", name: "Cocos Islands" },
    CO: { prefix: "+57", name: "Colombia" },
    KM: { prefix: "+269", name: "Comoros" },
    CG: { prefix: "+242", name: "Congo" },
    CD: { prefix: "+243", name: "Democratic Republic of the Congo" },
    CK: { prefix: "+682", name: "Cook Islands" },
    CR: { prefix: "+506", name: "Costa Rica" },
    CI: { prefix: "+225", name: "Cote d'Ivoire" },
    HR: { prefix: "+385", name: "Croatia" },
    CU: { prefix: "+53", name: "Cuba" },
    CW: { prefix: "+599", name: "Curaçao" },
    CY: { prefix: "+357", name: "Cyprus" },
    CZ: { prefix: "+420", name: "Czech Republic" },
    DK: { prefix: "+45", name: "Denmark" },
    DJ: { prefix: "+253", name: "Djibouti" },
    DM: { prefix: "+1-767", name: "Dominica" },
    DO: { prefix: "+1-809", name: "Dominican Republic" },
    EC: { prefix: "+593", name: "Ecuador" },
    EG: { prefix: "+20", name: "Egypt" },
    SV: { prefix: "+503", name: "El Salvador" },
    GQ: { prefix: "+240", name: "Equatorial Guinea" },
    ER: { prefix: "+291", name: "Eritrea" },
    EE: { prefix: "+372", name: "Estonia" },
    ET: { prefix: "+251", name: "Ethiopia" },
    FK: { prefix: "+500", name: "Falkland Islands" },
    FO: { prefix: "+298", name: "Faroe Islands" },
    FJ: { prefix: "+679", name: "Fiji" },
    FI: { prefix: "+358", name: "Finland" },
    FR: { prefix: "+33", name: "France" },
    GF: { prefix: "+594", name: "French Guiana" },
    PF: { prefix: "+689", name: "French Polynesia" },
    GA: { prefix: "+241", name: "Gabon" },
    GM: { prefix: "+220", name: "Gambia" },
    GE: { prefix: "+995", name: "Georgia" },
    DE: { prefix: "+49", name: "Germany" },
    GH: { prefix: "+233", name: "Ghana" },
    GI: { prefix: "+350", name: "Gibraltar" },
    GR: { prefix: "+30", name: "Greece" },
    GL: { prefix: "+299", name: "Greenland" },
    GD: { prefix: "+1-473", name: "Grenada" },
    GP: { prefix: "+590", name: "Guadeloupe" },
    GU: { prefix: "+1-671", name: "Guam" },
    GT: { prefix: "+502", name: "Guatemala" },
    GG: { prefix: "+44-1481", name: "Guernsey" },
    GN: { prefix: "+224", name: "Guinea" },
    GW: { prefix: "+245", name: "Guinea-Bissau" },
    GY: { prefix: "+592", name: "Guyana" },
    HT: { prefix: "+509", name: "Haiti" },
    HN: { prefix: "+504", name: "Honduras" },
    HK: { prefix: "+852", name: "Hong Kong" },
    HU: { prefix: "+36", name: "Hungary" },
    IS: { prefix: "+354", name: "Iceland" },
    IN: { prefix: "+91", name: "India" },
    ID: { prefix: "+62", name: "Indonesia" },
    IR: { prefix: "+98", name: "Iran" },
    IQ: { prefix: "+964", name: "Iraq" },
    IE: { prefix: "+353", name: "Ireland" },
    IM: { prefix: "+44-1624", name: "Isle of Man" },
    IL: { prefix: "+972", name: "Israel" },
    IT: { prefix: "+39", name: "Italy" },
    JM: { prefix: "+1-876", name: "Jamaica" },
    JP: { prefix: "+81", name: "Japan" },
    JE: { prefix: "+44-1534", name: "Jersey" },
    JO: { prefix: "+962", name: "Jordan" },
    KZ: { prefix: "+7", name: "Kazakhstan" },
    KE: { prefix: "+254", name: "Kenya" },
    KI: { prefix: "+686", name: "Kiribati" },
    KW: { prefix: "+965", name: "Kuwait" },
    KG: { prefix: "+996", name: "Kyrgyzstan" },
    LA: { prefix: "+856", name: "Laos" },
    LV: { prefix: "+371", name: "Latvia" },
    LB: { prefix: "+961", name: "Lebanon" },
    LS: { prefix: "+266", name: "Lesotho" },
    LR: { prefix: "+231", name: "Liberia" },
    LY: { prefix: "+218", name: "Libya" },
    LI: { prefix: "+423", name: "Liechtenstein" },
    LT: { prefix: "+370", name: "Lithuania" },
    LU: { prefix: "+352", name: "Luxembourg" },
    MO: { prefix: "+853", name: "Macau" },
    MK: { prefix: "+389", name: "North Macedonia" },
    MG: { prefix: "+261", name: "Madagascar" },
    MW: { prefix: "+265", name: "Malawi" },
    MY: { prefix: "+60", name: "Malaysia" },
    MV: { prefix: "+960", name: "Maldives" },
    ML: { prefix: "+223", name: "Mali" },
    MT: { prefix: "+356", name: "Malta" },
    MH: { prefix: "+692", name: "Marshall Islands" },
    MQ: { prefix: "+596", name: "Martinique" },
    MR: { prefix: "+222", name: "Mauritania" },
    MU: { prefix: "+230", name: "Mauritius" },
    YT: { prefix: "+262", name: "Mayotte" },
    MX: { prefix: "+52", name: "Mexico" },
    FM: { prefix: "+691", name: "Micronesia" },
    MD: { prefix: "+373", name: "Moldova" },
    MC: { prefix: "+377", name: "Monaco" },
    MN: { prefix: "+976", name: "Mongolia" },
    ME: { prefix: "+382", name: "Montenegro" },
    MS: { prefix: "+1-664", name: "Montserrat" },
    MA: { prefix: "+212", name: "Morocco" },
    MZ: { prefix: "+258", name: "Mozambique" },
    MM: { prefix: "+95", name: "Myanmar" },
    NA: { prefix: "+264", name: "Namibia" },
    NR: { prefix: "+674", name: "Nauru" },
    NP: { prefix: "+977", name: "Nepal" },
    NL: { prefix: "+31", name: "Netherlands" },
    NC: { prefix: "+687", name: "New Caledonia" },
    NZ: { prefix: "+64", name: "New Zealand" },
    NI: { prefix: "+505", name: "Nicaragua" },
    NE: { prefix: "+227", name: "Niger" },
    NG: { prefix: "+234", name: "Nigeria" },
    NU: { prefix: "+683", name: "Niue" },
    NF: { prefix: "+672", name: "Norfolk Island" },
    KP: { prefix: "+850", name: "North Korea" },
    MP: { prefix: "+1-670", name: "Northern Mariana Islands" },
    NO: { prefix: "+47", name: "Norway" },
    OM: { prefix: "+968", name: "Oman" },
    PK: { prefix: "+92", name: "Pakistan" },
    PW: { prefix: "+680", name: "Palau" },
    PS: { prefix: "+970", name: "Palestine" },
    PA: { prefix: "+507", name: "Panama" },
    PG: { prefix: "+675", name: "Papua New Guinea" },
    PY: { prefix: "+595", name: "Paraguay" },
    PE: { prefix: "+51", name: "Peru" },
    PH: { prefix: "+63", name: "Philippines" },
    PL: { prefix: "+48", name: "Poland" },
    PT: { prefix: "+351", name: "Portugal" },
    PR: { prefix: "+1-787", name: "Puerto Rico" },
    QA: { prefix: "+974", name: "Qatar" },
    RE: { prefix: "+262", name: "Réunion" },
    RO: { prefix: "+40", name: "Romania" },
    RU: { prefix: "+7", name: "Russia" },
    RW: { prefix: "+250", name: "Rwanda" },
    BL: { prefix: "+590", name: "Saint Barthélemy" },
    SH: { prefix: "+290", name: "Saint Helena" },
    KN: { prefix: "+1-869", name: "Saint Kitts and Nevis" },
    LC: { prefix: "+1-758", name: "Saint Lucia" },
    MF: { prefix: "+590", name: "Saint Martin" },
    PM: { prefix: "+508", name: "Saint Pierre and Miquelon" },
    VC: { prefix: "+1-784", name: "Saint Vincent and the Grenadines" },
    WS: { prefix: "+685", name: "Samoa" },
    SM: { prefix: "+378", name: "San Marino" },
    ST: { prefix: "+239", name: "Sao Tome and Principe" },
    SA: { prefix: "+966", name: "Saudi Arabia" },
    SN: { prefix: "+221", name: "Senegal" },
    RS: { prefix: "+381", name: "Serbia" },
    SC: { prefix: "+248", name: "Seychelles" },
    SL: { prefix: "+232", name: "Sierra Leone" },
    SG: { prefix: "+65", name: "Singapore" },
    SX: { prefix: "+1-721", name: "Sint Maarten" },
    SK: { prefix: "+421", name: "Slovakia" },
    SI: { prefix: "+386", name: "Slovenia" },
    SB: { prefix: "+677", name: "Solomon Islands" },
    SO: { prefix: "+252", name: "Somalia" },
    ZA: { prefix: "+27", name: "South Africa" },
    GS: { prefix: "+500", name: "South Georgia and the South Sandwich Islands" },
    KR: { prefix: "+82", name: "South Korea" },
    SS: { prefix: "+211", name: "South Sudan" },
    ES: { prefix: "+34", name: "Spain" },
    LK: { prefix: "+94", name: "Sri Lanka" },
    SD: { prefix: "+249", name: "Sudan" },
    SR: { prefix: "+597", name: "Suriname" },
    SJ: { prefix: "+47", name: "Svalbard and Jan Mayen" },
    SZ: { prefix: "+268", name: "Eswatini" },
    SE: { prefix: "+46", name: "Sweden" },
    CH: { prefix: "+41", name: "Switzerland" },
    SY: { prefix: "+963", name: "Syria" },
    TW: { prefix: "+886", name: "Taiwan" },
    TJ: { prefix: "+992", name: "Tajikistan" },
    TZ: { prefix: "+255", name: "Tanzania" },
    TH: { prefix: "+66", name: "Thailand" },
    TL: { prefix: "+670", name: "Timor-Leste" },
    TG: { prefix: "+228", name: "Togo" },
    TK: { prefix: "+690", name: "Tokelau" },
    TO: { prefix: "+676", name: "Tonga" },
    TT: { prefix: "+1-868", name: "Trinidad and Tobago" },
    TN: { prefix: "+216", name: "Tunisia" },
    TR: { prefix: "+90", name: "Turkey" },
    TM: { prefix: "+993", name: "Turkmenistan" },
    TC: { prefix: "+1-649", name: "Turks and Caicos Islands" },
    TV: { prefix: "+688", name: "Tuvalu" },
    UG: { prefix: "+256", name: "Uganda" },
    UA: { prefix: "+380", name: "Ukraine" },
    AE: { prefix: "+971", name: "United Arab Emirates" },
    GB: { prefix: "+44", name: "United Kingdom" },
    US: { prefix: "+1", name: "United States" },
    UY: { prefix: "+598", name: "Uruguay" },
    UZ: { prefix: "+998", name: "Uzbekistan" },
    VU: { prefix: "+678", name: "Vanuatu" },
    VA: { prefix: "+379", name: "Vatican City" },
    VE: { prefix: "+58", name: "Venezuela" },
    VN: { prefix: "+84", name: "Vietnam" },
    WF: { prefix: "+681", name: "Wallis and Futuna" },
    EH: { prefix: "+212", name: "Western Sahara" },
    YE: { prefix: "+967", name: "Yemen" },
    ZM: { prefix: "+260", name: "Zambia" },
    ZW: { prefix: "+263", name: "Zimbabwe" },
  }
}
