name: Build, lint and test

on: [push]

jobs:
  test:
    name: "Build, lint and test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
