name: Build, lint and test

on: [ push ]

jobs:
  test:
    name: "Build, lint and test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-

      - name: Configure git for private modules
        env:
          PO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PO_GITHUB_USER: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          git config \
           --global url."https://${PO_GITHUB_USER}:${PO_GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Check package.json version changed
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const diff = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.before,
              head: context.payload.after,
            });

            if (!diff.data.files) {
              core.info('No files changed in this Pull Request.');
              return;
            }
            const packageJsonDiff = diff.data.files.find(file => file.filename === 'package.json');
            if (!packageJsonDiff) {
              core.setFailed('package.json file has not been modified in this Pull Request. Bump the version using `yarn bump-version` command.');
              return;
            }

            const versionChangeRegex = /"version":\s*"(.+)"/;
            const oldVersionMatch = versionChangeRegex.exec(packageJsonDiff.patch.split('\n').find(line => line.startsWith('-')));
            const newVersionMatch = versionChangeRegex.exec(packageJsonDiff.patch.split('\n').find(line => line.startsWith('+')));


            if (!oldVersionMatch || !newVersionMatch || oldVersionMatch[1] === newVersionMatch[1]) {
              core.setFailed('The version in package.json has not been modified. Bump the version using `yarn bump-version` command.');
              return;
            }

            core.info('Version check passed.');

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
